server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway
  
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway-9527.com     # 自定义服务名称信息
    prefer-ip-address: true           #访问路径可以显示IP信息
    
    
info: 
  app.name: hu-microservicecloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
zuul: 
  prefix: /huy
  ignored-services: "*"
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**