server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.hu.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: root
    dbcp2:
      min-idle: 5
      max-idle: 5
      initial-size: 5
      max-wait-millis: 200  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8002     # 自定义服务名称信息
    prefer-ip-address: true           #访问路径可以显示IP信息
info: 
  app.name: hu-microservicecloud
  company.name: www.baidu.com
  build.artifactId: microservicecloud-provider-dept-8002
  build.version: 0.0.1-SNAPSHOT
  