server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud: 
    config:
      server:
        git:
          uri: git@github.com:huyang8809/microservicecloud-config.git  #github上git仓库名字